"""Refactor Exercise table

Revision ID: 0b95d16c99d5
Revises: 243c35969c01
Create Date: 2026-04-29 19:10:16.830654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b95d16c99d5'
down_revision: Union[str, Sequence[str], None] = '243c35969c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    exercise_category = sa.Enum('strength', 'cardio', 'flexibility', 'balance', 'recovery', name='exercisecategory')
    exercise_category.create(op.get_bind(), checkfirst=True)
    exercise_difficulty = sa.Enum('beginner', 'intermediate', 'advanced', name='exercisedifficulty')
    exercise_difficulty.create(op.get_bind(), checkfirst=True)

    op.add_column('exercise', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('exercise', sa.Column('category', exercise_category, nullable=False))
    op.add_column('exercise', sa.Column('muscleGroups', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('secondaryMuscles', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('equipmentRequired', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('difficulty', exercise_difficulty, nullable=False))
    op.add_column('exercise', sa.Column('contraindicatedInjuries', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('instructions', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('tips', sa.JSON(), nullable=True))
    op.add_column('exercise', sa.Column('imageUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('exercise', sa.Column('videoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('exercise', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('exercise', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('exercise', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('exerciselog_exercise_id_fkey', 'exerciselog', type_='foreignkey')
    op.alter_column('exercise', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('exercise', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_index(op.f('ix_exercise_slug'), 'exercise', ['slug'], unique=True)
    op.drop_column('exercise', 'tutorialUrl')
    op.drop_column('exercise', 'type')
    op.alter_column('exerciselog', 'exercise_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='exercise_id::uuid')
    op.create_foreign_key('exerciselog_exercise_id_fkey', 'exerciselog', 'exercise', ['exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exerciselog', 'exercise_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('exercise', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exercise', sa.Column('tutorialUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exercise_slug'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.alter_column('exercise', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('exercise', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('exercise', 'updatedAt')
    op.drop_column('exercise', 'createdAt')
    op.drop_column('exercise', 'isActive')
    op.drop_column('exercise', 'videoUrl')
    op.drop_column('exercise', 'imageUrl')
    op.drop_column('exercise', 'tips')
    op.drop_column('exercise', 'instructions')
    op.drop_column('exercise', 'contraindicatedInjuries')
    op.drop_column('exercise', 'difficulty')
    op.drop_column('exercise', 'equipmentRequired')
    op.drop_column('exercise', 'secondaryMuscles')
    op.drop_column('exercise', 'muscleGroups')
    op.drop_column('exercise', 'category')
    op.drop_column('exercise', 'slug')
    # ### end Alembic commands ###
