"""remove gamification

Revision ID: 243c35969c01
Revises: 8b2328d92477
Create Date: 2026-04-29 08:05:16.243178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '243c35969c01'
down_revision: Union[str, Sequence[str], None] = '8b2328d92477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personalrecord_user_id'), table_name='personalrecord')
    op.drop_table('personalrecord')
    op.drop_index(op.f('ix_userbadge_user_id'), table_name='userbadge')
    op.drop_index(op.f('ix_userachievement_user_id'), table_name='userachievement')
    op.drop_index(op.f('ix_leaderboardsnapshot_user_id'), table_name='leaderboardsnapshot')
    op.drop_table('leaderboardsnapshot')
    op.alter_column('chatmessage', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('exercise', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('exercise', 'base_xp')
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_constraint(op.f('user_activeBadgeId_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'activeBadgeId')
    op.drop_column('userstats', 'currentLevel')
    op.drop_column('userstats', 'totalXp')
    op.drop_column('workoutsession', 'total_xp_earned')
    op.drop_table('userachievement')
    op.drop_table('userbadge')
    op.drop_table('achievement')
    op.drop_table('badge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requirement', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('iconUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('badge_pkey'))
    )
    op.create_table('achievement',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('iconUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('achievement_pkey'))
    )
    op.add_column('workoutsession', sa.Column('total_xp_earned', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('userstats', sa.Column('totalXp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('userstats', sa.Column('currentLevel', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('activeBadgeId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_activeBadgeId_fkey'), 'user', 'badge', ['activeBadgeId'], ['id'])
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('exercise', sa.Column('base_xp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('exercise', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chatmessage', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('leaderboardsnapshot',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('leaderboardsnapshot_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leaderboardsnapshot_pkey')),
    sa.UniqueConstraint('user_id', 'week_start', 'exercise_type', name=op.f('uq_leaderboard_snapshot'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_leaderboardsnapshot_user_id'), 'leaderboardsnapshot', ['user_id'], unique=False)
    op.create_table('userachievement',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('achievement_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('earnedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], name=op.f('userachievement_achievement_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('userachievement_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userachievement_pkey')),
    sa.UniqueConstraint('user_id', 'achievement_id', name=op.f('uq_userachievement'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_userachievement_user_id'), 'userachievement', ['user_id'], unique=False)
    op.create_table('userbadge',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('badge_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('earnedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], name=op.f('userbadge_badge_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('userbadge_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userbadge_pkey')),
    sa.UniqueConstraint('user_id', 'badge_id', name=op.f('uq_userbadge'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_userbadge_user_id'), 'userbadge', ['user_id'], unique=False)
    op.create_index(op.f('ix_userbadge_user_id'), 'userbadge', ['user_id'], unique=False)
    op.create_table('personalrecord',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('best_reps_in_session', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achieved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('personalrecord_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('personalrecord_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('personalrecord_pkey')),
    sa.UniqueConstraint('user_id', 'exercise_id', name=op.f('uq_personalrecord'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_personalrecord_user_id'), 'personalrecord', ['user_id'], unique=False)
    op.create_index(op.f('ix_personalrecord_user_id'), 'personalrecord', ['user_id'], unique=False)
    # ### end Alembic commands ###
