"""Refined schema: snake_case columns, check constraints, and relational plan schedule

Revision ID: 2f6ca54a39dc
Revises: b464caf01c41
Create Date: 2026-05-03 15:24:25.151546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2f6ca54a39dc'
down_revision: Union[str, Sequence[str], None] = 'b464caf01c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types manually because alembic alter_column doesn't auto-create them
    bind = op.get_bind()
    postgresql.ENUM('weight_loss', 'muscle_gain', 'maintain', name='goalenum').create(bind)
    postgresql.ENUM('level_1', 'level_2', 'level_3', name='difficultylevelenum').create(bind)
    postgresql.ENUM('male', 'female', name='genderenum').create(bind)
    postgresql.ENUM('beginner', 'intermediate', 'advanced', name='skilllevelenum').create(bind)
    postgresql.ENUM('low', 'medium', 'high', name='intensityenum').create(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_day',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['exerciseplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_day_plan_id'), 'plan_day', ['plan_id'], unique=False)
    op.create_table('plan_day_exercise',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_day_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_day_exercise_plan_day_id'), 'plan_day_exercise', ['plan_day_id'], unique=False)
    op.alter_column('chatmessage', 'createdAt', new_column_name='created_at')
    op.alter_column('chatsession', 'createdAt', new_column_name='created_at')
    op.alter_column('chatsession', 'updatedAt', new_column_name='updated_at')
    op.alter_column('dailylog', 'createdAt', new_column_name='created_at')
    op.alter_column('exercise', 'muscleGroups', new_column_name='muscle_groups')
    op.alter_column('exercise', 'secondaryMuscles', new_column_name='secondary_muscles')
    op.alter_column('exercise', 'equipmentRequired', new_column_name='equipment_required')
    op.alter_column('exercise', 'imageUrl', new_column_name='image_url')
    op.alter_column('exercise', 'videoUrl', new_column_name='video_url')
    op.alter_column('exercise', 'isActive', new_column_name='is_active')
    op.alter_column('exercise', 'createdAt', new_column_name='created_at')
    op.alter_column('exercise', 'updatedAt', new_column_name='updated_at')
    op.alter_column('exerciselog', 'createdAt', new_column_name='created_at')
    op.alter_column('exerciseplan', 'createdAt', new_column_name='created_at')
    op.alter_column('exerciseplan', 'updatedAt', new_column_name='updated_at')
    op.alter_column('exerciseplan', 'goal',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('weight_loss', 'muscle_gain', 'maintain', name='goalenum'),
               existing_nullable=False, postgresql_using="goal::goalenum")
    op.alter_column('exerciseplan', 'difficulty_level',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('level_1', 'level_2', 'level_3', name='difficultylevelenum'),
               existing_nullable=False, postgresql_using="difficulty_level::difficultylevelenum")
    op.drop_column('exerciseplan', 'schedule_json')
    op.alter_column('passwordresettoken', 'expiresAt', new_column_name='expires_at')
    op.alter_column('passwordresettoken', 'usedAt', new_column_name='used_at')
    op.alter_column('passwordresettoken', 'createdAt', new_column_name='created_at')
    op.alter_column('user', 'authProvider', new_column_name='auth_provider')
    op.alter_column('user', 'googleId', new_column_name='google_id')
    op.alter_column('user', 'photoUrl', new_column_name='photo_url')
    op.alter_column('user', 'notificationEnabled', new_column_name='notification_enabled')
    op.alter_column('user', 'deletedAt', new_column_name='deleted_at')
    op.alter_column('user', 'createdAt', new_column_name='created_at')
    op.alter_column('user', 'updatedAt', new_column_name='updated_at')
    op.drop_constraint(op.f('user_googleId_key'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['google_id'])
    op.alter_column('userfitnessprofile', 'skillLevel', new_column_name='skill_level')
    op.alter_column('userfitnessprofile', 'fcsScoreRaw', new_column_name='fcs_score_raw')
    op.alter_column('userfitnessprofile', 'difficultyLevel', new_column_name='difficulty_level')
    op.alter_column('userfitnessprofile', 'createdAt', new_column_name='created_at')
    op.alter_column('userfitnessprofile', 'updatedAt', new_column_name='updated_at')
    op.alter_column('userfitnessprofile', 'goal',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('weight_loss', 'muscle_gain', 'maintain', name='goalenum'),
               existing_nullable=False, postgresql_using="goal::goalenum")
    op.alter_column('userfitnessprofile', 'gender',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('male', 'female', name='genderenum'),
               existing_nullable=False, postgresql_using="gender::genderenum")
    op.alter_column('userfitnessprofile', 'intensity',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('low', 'medium', 'high', name='intensityenum'),
               existing_nullable=False, postgresql_using="intensity::intensityenum")
    op.alter_column('userstats', 'currentStreak', new_column_name='current_streak')
    op.alter_column('userstats', 'longestStreak', new_column_name='longest_streak')
    op.alter_column('userstats', 'lastActiveDate', new_column_name='last_active_date')
    op.alter_column('userstats', 'totalPushUps', new_column_name='total_push_ups')
    op.alter_column('userstats', 'totalSitUps', new_column_name='total_sit_ups')
    op.alter_column('userstats', 'updatedAt', new_column_name='updated_at')
    op.alter_column('workoutsession', 'createdAt', new_column_name='created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workoutsession', 'created_at', new_column_name='createdAt')
    op.alter_column('userstats', 'total_push_ups', new_column_name='totalPushUps')
    op.alter_column('userstats', 'current_streak', new_column_name='currentStreak')
    op.alter_column('userstats', 'last_active_date', new_column_name='lastActiveDate')
    op.alter_column('userstats', 'updated_at', new_column_name='updatedAt')
    op.alter_column('userstats', 'total_sit_ups', new_column_name='totalSitUps')
    op.alter_column('userstats', 'longest_streak', new_column_name='longestStreak')
    op.alter_column('userfitnessprofile', 'difficulty_level', new_column_name='difficultyLevel')
    op.alter_column('userfitnessprofile', 'created_at', new_column_name='createdAt')
    op.alter_column('userfitnessprofile', 'skill_level', new_column_name='skillLevel')
    op.alter_column('userfitnessprofile', 'fcs_score_raw', new_column_name='fcsScoreRaw')
    op.alter_column('userfitnessprofile', 'updated_at', new_column_name='updatedAt')
    op.alter_column('userfitnessprofile', 'intensity',
               existing_type=sa.Enum('low', 'medium', 'high', name='intensityenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('userfitnessprofile', 'gender',
               existing_type=sa.Enum('male', 'female', name='genderenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('userfitnessprofile', 'goal',
               existing_type=sa.Enum('weight_loss', 'muscle_gain', 'maintain', name='goalenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('user', 'auth_provider', new_column_name='authProvider')
    op.alter_column('user', 'photo_url', new_column_name='photoUrl')
    op.alter_column('user', 'created_at', new_column_name='createdAt')
    op.alter_column('user', 'deleted_at', new_column_name='deletedAt')
    op.alter_column('user', 'updated_at', new_column_name='updatedAt')
    op.alter_column('user', 'notification_enabled', new_column_name='notificationEnabled')
    op.alter_column('user', 'google_id', new_column_name='googleId')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('user_googleId_key'), 'user', ['googleId'], postgresql_nulls_not_distinct=False)
    op.alter_column('passwordresettoken', 'created_at', new_column_name='createdAt')
    op.alter_column('passwordresettoken', 'expires_at', new_column_name='expiresAt')
    op.alter_column('passwordresettoken', 'used_at', new_column_name='usedAt')
    op.alter_column('exerciseplan', 'created_at', new_column_name='createdAt')
    op.alter_column('exerciseplan', 'updated_at', new_column_name='updatedAt')
    op.add_column('exerciseplan', sa.Column('schedule_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('exerciseplan', 'difficulty_level',
               existing_type=sa.Enum('level_1', 'level_2', 'level_3', name='difficultylevelenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('exerciseplan', 'goal',
               existing_type=sa.Enum('weight_loss', 'muscle_gain', 'maintain', name='goalenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('exerciselog', 'created_at', new_column_name='createdAt')
    op.alter_column('exercise', 'video_url', new_column_name='videoUrl')
    op.alter_column('exercise', 'secondary_muscles', new_column_name='secondaryMuscles')
    op.alter_column('exercise', 'equipment_required', new_column_name='equipmentRequired')
    op.alter_column('exercise', 'created_at', new_column_name='createdAt')
    op.alter_column('exercise', 'is_active', new_column_name='isActive')
    op.alter_column('exercise', 'muscle_groups', new_column_name='muscleGroups')
    op.alter_column('exercise', 'updated_at', new_column_name='updatedAt')
    op.alter_column('exercise', 'image_url', new_column_name='imageUrl')
    op.alter_column('dailylog', 'created_at', new_column_name='createdAt')
    op.alter_column('chatsession', 'created_at', new_column_name='createdAt')
    op.alter_column('chatsession', 'updated_at', new_column_name='updatedAt')
    op.alter_column('chatmessage', 'created_at', new_column_name='createdAt')
    op.drop_index(op.f('ix_plan_day_exercise_plan_day_id'), table_name='plan_day_exercise')
    op.drop_table('plan_day_exercise')
    op.drop_index(op.f('ix_plan_day_plan_id'), table_name='plan_day')
    op.drop_table('plan_day')
    # ### end Alembic commands ###
