"""add form mistakes

Revision ID: 904611c3bc81
Revises: fb3273ca153c
Create Date: 2026-07-10 14:46:16.294159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904611c3bc81'
down_revision: Union[str, Sequence[str], None] = 'fb3273ca153c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exerciselog', sa.Column('form_mistakes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exerciselog', 'form_mistakes')
    # ### end Alembic commands ###
