"""add nutrition tables

Revision ID: adf1650e9612
Revises: d8b7c2a9416e
Create Date: 2026-06-14 20:47:33.453994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adf1650e9612'
down_revision: Union[str, Sequence[str], None] = 'd8b7c2a9416e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fooditem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('calories_per_serving', sa.Float(), nullable=False),
    sa.Column('protein_per_serving', sa.Float(), nullable=False),
    sa.Column('carbs_per_serving', sa.Float(), nullable=False),
    sa.Column('fat_per_serving', sa.Float(), nullable=False),
    sa.Column('serving_unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fooditem_name'), 'fooditem', ['name'], unique=False)
    op.create_table('foodlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('food_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['fooditem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodlog_date'), 'foodlog', ['date'], unique=False)
    op.create_index(op.f('ix_foodlog_food_item_id'), 'foodlog', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_foodlog_user_id'), 'foodlog', ['user_id'], unique=False)
    op.create_table('nutritionsummary',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_kcal', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_nutritionsummary_user_date')
    )
    op.create_index(op.f('ix_nutritionsummary_date'), 'nutritionsummary', ['date'], unique=False)
    op.create_index(op.f('ix_nutritionsummary_user_id'), 'nutritionsummary', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutritionsummary_user_id'), table_name='nutritionsummary')
    op.drop_index(op.f('ix_nutritionsummary_date'), table_name='nutritionsummary')
    op.drop_table('nutritionsummary')
    op.drop_index(op.f('ix_foodlog_user_id'), table_name='foodlog')
    op.drop_index(op.f('ix_foodlog_food_item_id'), table_name='foodlog')
    op.drop_index(op.f('ix_foodlog_date'), table_name='foodlog')
    op.drop_table('foodlog')
    op.drop_index(op.f('ix_fooditem_name'), table_name='fooditem')
    op.drop_table('fooditem')
    # ### end Alembic commands ###
