"""update_onboarding_parameters

Revision ID: b464caf01c41
Revises: b13dcea86d07
Create Date: 2026-05-02 16:37:26.405258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b464caf01c41'
down_revision: Union[str, Sequence[str], None] = 'b13dcea86d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exerciseplan', 'progression_modifier')
    op.drop_column('exerciseplan', 'duration_target')
    op.add_column('userfitnessprofile', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('userfitnessprofile', sa.Column('bmr', sa.Float(), nullable=False))
    op.add_column('userfitnessprofile', sa.Column('tdee', sa.Float(), nullable=False))
    op.add_column('userfitnessprofile', sa.Column('target_daily_kcal', sa.Float(), nullable=False))
    op.add_column('userfitnessprofile', sa.Column('macros_json', sa.JSON(), nullable=True))
    op.add_column('userfitnessprofile', sa.Column('difficulty_gate_applied', sa.Boolean(), nullable=False))
    op.drop_column('userfitnessprofile', 'durationTarget')
    op.drop_column('userfitnessprofile', 'fcsScoreDowngraded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfitnessprofile', sa.Column('fcsScoreDowngraded', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('userfitnessprofile', sa.Column('durationTarget', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('userfitnessprofile', 'difficulty_gate_applied')
    op.drop_column('userfitnessprofile', 'macros_json')
    op.drop_column('userfitnessprofile', 'target_daily_kcal')
    op.drop_column('userfitnessprofile', 'tdee')
    op.drop_column('userfitnessprofile', 'bmr')
    op.drop_column('userfitnessprofile', 'gender')
    op.add_column('exerciseplan', sa.Column('duration_target', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exerciseplan', sa.Column('progression_modifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
