"""add duration_seconds to exerciselog

Revision ID: cf98ba820d5d
Revises: 904611c3bc81
Create Date: 2026-07-10 18:00:34.495908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf98ba820d5d'
down_revision: Union[str, Sequence[str], None] = '904611c3bc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exerciselog', sa.Column('duration_seconds', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exerciselog', 'duration_seconds')
    # ### end Alembic commands ###
